// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzjEiAGX_KvKox7LvRQwSdte1IIfEUJnY',
    appId: '1:881299891866:web:f649ea63ce32cf3af8e123',
    messagingSenderId: '881299891866',
    projectId: 'crud-flutter-firebase-27db5',
    authDomain: 'crud-flutter-firebase-27db5.firebaseapp.com',
    storageBucket: 'crud-flutter-firebase-27db5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjMBbnIgqDuKnVEuxqe-El6x5BysghguM',
    appId: '1:881299891866:android:a938819ea0bb65e8f8e123',
    messagingSenderId: '881299891866',
    projectId: 'crud-flutter-firebase-27db5',
    storageBucket: 'crud-flutter-firebase-27db5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZTfGWZ6ifDNInSfEasgYTRFcj3Va0MI',
    appId: '1:881299891866:ios:98bb642d9fa4538ef8e123',
    messagingSenderId: '881299891866',
    projectId: 'crud-flutter-firebase-27db5',
    storageBucket: 'crud-flutter-firebase-27db5.appspot.com',
    iosClientId: '881299891866-13h73dfo832la9vt5le2oeti5n3fqe6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZTfGWZ6ifDNInSfEasgYTRFcj3Va0MI',
    appId: '1:881299891866:ios:98bb642d9fa4538ef8e123',
    messagingSenderId: '881299891866',
    projectId: 'crud-flutter-firebase-27db5',
    storageBucket: 'crud-flutter-firebase-27db5.appspot.com',
    iosClientId: '881299891866-13h73dfo832la9vt5le2oeti5n3fqe6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
